// Package Bimah provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package models

import (
	"time"
)

// Fleet defines model for fleet.
type Fleet struct {
	CreationDate *time.Time `json:"creationDate,omitempty"`
	Endpoints    *[]string  `json:"endpoints,omitempty"`
	Id           *int       `json:"id,omitempty"`
	Tags         *[]string  `json:"tags,omitempty"`
}

// Path defines model for path.
type Path struct {
	CreationDate *time.Time `json:"creationDate,omitempty"`
	FleetId      *int       `json:"fleetId,omitempty"`
	Id           *int       `json:"id,omitempty"`
	Path         *string    `json:"path,omitempty"`
	RuleId       *int       `json:"ruleId,omitempty"`
	Tags         *[]string  `json:"tags,omitempty"`
}

// Rule defines model for rule.
type Rule struct {
	CreationDate *time.Time `json:"creationDate,omitempty"`
	Host         *string    `json:"host,omitempty"`
	Id           *int       `json:"id,omitempty"`
	Tags         *[]string  `json:"tags,omitempty"`
}

// Tlsconfig defines model for tlsconfig.
type Tlsconfig struct {
	Certificate  *string    `json:"certificate,omitempty"`
	CreationDate *time.Time `json:"creationDate,omitempty"`
	Hosts        *[]string  `json:"hosts,omitempty"`
	Id           *int       `json:"id,omitempty"`
	PrivateKey   *string    `json:"privateKey,omitempty"`
	Tags         *[]string  `json:"tags,omitempty"`
}

// PostFleetJSONBody defines parameters for PostFleet.
type PostFleetJSONBody struct {
	Due  *time.Time `json:"due,omitempty"`
	Tags *[]string  `json:"tags,omitempty"`
	Text *string    `json:"text,omitempty"`
}

// PostPathJSONBody defines parameters for PostPath.
type PostPathJSONBody struct {
	Due  *time.Time `json:"due,omitempty"`
	Tags *[]string  `json:"tags,omitempty"`
	Text *string    `json:"text,omitempty"`
}

// PostRuleJSONBody defines parameters for PostRule.
type PostRuleJSONBody struct {
	Due  *time.Time `json:"due,omitempty"`
	Tags *[]string  `json:"tags,omitempty"`
	Text *string    `json:"text,omitempty"`
}

// PostTlsconfigJSONBody defines parameters for PostTlsconfig.
type PostTlsconfigJSONBody struct {
	Due  *time.Time `json:"due,omitempty"`
	Tags *[]string  `json:"tags,omitempty"`
	Text *string    `json:"text,omitempty"`
}

// PostFleetJSONRequestBody defines body for PostFleet for application/json ContentType.
type PostFleetJSONRequestBody PostFleetJSONBody

// PostPathJSONRequestBody defines body for PostPath for application/json ContentType.
type PostPathJSONRequestBody PostPathJSONBody

// PostRuleJSONRequestBody defines body for PostRule for application/json ContentType.
type PostRuleJSONRequestBody PostRuleJSONBody

// PostTlsconfigJSONRequestBody defines body for PostTlsconfig for application/json ContentType.
type PostTlsconfigJSONRequestBody PostTlsconfigJSONBody

